### PR TITLE
Fix for KB4041678 KB4041681 by switching the default engine to ACE 12

### PR DESCRIPTION
**Pull request by streppelchen**
Switching the default engine to ACE 12, since according to wikipedia, ACE12 supports every format that OLEDB 4 does [https://en.wikipedia.org/wiki/Microsoft_Jet_Database_Engine](url)

Tests updated and all passed

### CODE REVIEW

**Comment by mrworkman** [comment]
I will have to review this. Switching to ace doesn't really fix the problem, it just works around it. I need to find out **why** the Jet database engine's not working.

**Comment by streppelchen** [comment]
sure, fixing the underlying problem would be better, but since microsoft "fixed" the Jet engine to stop working, and Ace supports everything Jet does, i'm not sure why one would want to keep using Jet.

That doesn't mean that there is no use case that i don't know of, that requires this.

**Comment by mrworkman** [comment]
The main argument in favour of using Jet is that (with 32-bit processes) you do not need to install any additional drivers (at least with Win 7 SP1 and up). Maybe this is important to some users.

Your solution does not correctly handle all cases where Jet could be used (for example, CSV will still use Jet by default). Additionally you've taken away the option of even using Jet anymore for `.xls` and other file-types.

Regardless, I want to give this more time (a week or two) to see if Microsoft responds with a fix (or rationale) for their breaking patch.

**Comment by anupvenugopal** [comment]
Just got an updated link from Microsoft.
They are not going to fix this.

https://blogs.msdn.microsoft.com/dataaccesstechnologies/2017/10/18/unexpected-error-from-external-database-driver-1-microsoft-jet-database-engine-after-applying-october-security-updates/

Anup

**Comment by mrworkman** [comment]
As already highlighted in issue #124 (which references the same article), yes Microsoft is planning to fix it:

>> Apart from this, Microsoft is working on a resolution and will provide an update in an upcoming release of the security patch. This is expected to be available in another 2-3 weeks or earlier.

**Comment by mrworkman** [comment]
Due to how long Jet has been deprecated, I have completely removed support for Jet from master. Closing this PR.

**Pull request closed without merging**
