### PR TITLE
MbUnit change to Nunit

### PR DESCRIPTION
**Pull request by cuongtranba**
I would like to use Nunit 3.0.1 , and i also change some function in test project to suit Nunit,
to run the test may need to install [NUnit3 Test Adapter](https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d)
please code review for me.

thanks.

### CODE REVIEW

**Comment by mrworkman** [comment]
I'm not sure where your motivation comes from... why do you want to make this change?

**Comment by achvaicer** [comment]
I can't respond for @cuongtranba, but I believe that the motivation is because MbUnit doesn't have any commit since 2013, while NUnit is mature for a long time and with constant evolution.

https://github.com/Gallio/mbunit-v3/commits/master

https://github.com/nunit/nunit/commits/master

I didn't found any extension adapter to test directly from VS 2015/2017. 

With NUnit, this project will be able to be built on a free build server like AppVeyor with no problems.

https://www.appveyor.com/docs/running-tests/

IMHO, is enough motivation.

**Comment by mrworkman** [comment]
I wasn't really questioning the merits of switching, but the OPs personal motivation. He hasn't made any other contributions to the project, so it seemed odd for this to be his first pull request.

The best reason to switch to Nunit these days is, as you mentioned, the ability to use tools like Appveyor. Along with this PR, I'd like to know if we can take Nant out of the picture too, since it's even older, and doesn't support C# 6.

@cuongtranba, if you're still around, can you resolve the current set of conflicts?

**Comment by cuongtranba** [comment]
@achvaicer You're correct 
@mrworkman Sorry for the late reply, I thought the project was not maintained anymore because I did the push request for long times ^^ , I will resolve the conflicts.

**Comment by mrworkman** [comment]
@cuongtranba, if you haven't started, don't worry about it. I'll take care of the conflicts myself.

**Comment by mrworkman** [comment]
Your changes have been pulled into the `mbunit-to-nunit` branch.

**Pull request merged**
