### PR TITLE
x86/x64 split no longer necessary

### PR DESCRIPTION
**Pull request by phawxby**

### CODE REVIEW

**Comment by phawxby** [comment]
Did this ever get implemented?

**Comment by devfrenzy** [comment]
@paulyoder please merge

**Comment by paulyoder** [comment]
@phawxby: Sorry, I don't have time to merge and upload a new package to nuget. I made you a collaborator, so you can merge this PR. Let me know your email, and I can make you an owner of the nuget packages too.

**Comment by phawxby** [comment]
I've never published to Nuget before, time to learn. phawxby@gmail.com

**Comment by paulyoder** [comment]
It looks like I need your NuGet.org user name to add you as an owner.
What's your Nuget username?

**Comment by phawxby** [comment]
Try phawxby, I've just registered.

**Pull request merged**
