### PR TITLE
Add row number and column name when an exception occurs.

### PR DESCRIPTION
**Pull request by clstopher**
I needed to see where a cast error was occurring, so I quickly added this information as Data fields on the thrown Exception.  Retrieve the data when an Exception occurs by catching the Exception and then looking at the `ex.Data["LinqToExcel.RowNumber"]` and `ex.Data["LinqToExcel.ColumnName"]` properties.

Noticed that someone else wanted it too (Issue #61), so here's a pull request.

### CODE REVIEW

**Comment by dclaze** [comment]
Bump.

**Comment by noremorse1** [comment]
Any news? Seems fairly basic to get the row/column that fails.

**Comment by Revenantus556** [comment]
I'd just like to voice my support for this request. I'm currently using this branch as the row and column numbers on exceptions are extremely helpful.

**Comment by achvaicer** [comment]
This is a very interesting and helpful feature to be added.

Does anyone pretend to approve this pull request?

**Comment by mrworkman** [comment]
I can review it, but you have to understand that the project maintainer doesn't have time anymore, and I have little time as well.

**Comment by mrworkman** [comment]
I'd like to see something like this get added too. But, personally, I'd rather not just add to the `Data` dictionary of any `Exception` thrown. I'd rather throw an appropriate exception (with Row/Column properties), and set its inner exception to the original exception. 

This PR is over 3 years old, so I don't think I can just ask the OP (@clstopher) to update it, or identify the exception that was being thrown any more. So, that's probably going to be down to me to fix up...

**Comment by achvaicer** [comment]
Created another pull request #125 throwing a customized Exception based on this solution.

**Comment by mrworkman** [comment]
Given the age of this original PR, I am closing it in favour of PR #125 as it is more up to date.

**Comment by achvaicer** [comment]
Just to reference issue #61 .

**Pull request closed without merging**
